# Generated by Django 5.2.2 on 2025-06-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="paid_course",
            field=models.CharField(
                blank=True,
                help_text="Укажите оплаченный курс.",
                max_length=250,
                null=True,
                verbose_name="Оплаченный курс",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_lesson",
            field=models.CharField(
                blank=True,
                help_text="Укажите оплаченный урок.",
                max_length=250,
                null=True,
                verbose_name="Оплаченный урок",
            ),
        ),
    ]
