# Generated by Django 5.2.2 on 2025-06-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_paid_course_alter_payment_paid_lesson"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": [
                    "user",
                    "payment_date",
                    "paid_course",
                    "paid_lesson",
                    "amount",
                    "payment_method",
                ],
                "verbose_name": "Платёж",
                "verbose_name_plural": "Платежи",
            },
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_amount",
        ),
        migrations.AddField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Укажите сумму оплаты.",
                max_digits=10,
                null=True,
                verbose_name="Сумма оплаты",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату.",
                max_length=400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите id ceccии.",
                max_length=255,
                null=True,
                verbose_name="Id сессии",
            ),
        ),
    ]
