# Generated by Django 5.2.2 on 2025-06-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_course_options_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ["user", "course"],
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="description",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="name",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="is_active_subscription",
            field=models.BooleanField(default=True, verbose_name="Признак подписки"),
        ),
    ]
