# Generated by Django 5.2.2 on 2025-06-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_alter_subscription_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Укажите цену курса.",
                max_digits=10,
                null=True,
                verbose_name="Цена",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Укажите цену урока.",
                max_digits=10,
                null=True,
                verbose_name="Цена",
            ),
        ),
    ]
